[package]
name = "table-filter"
version = "0.3.0"
edition = "2024"

[[bin]]
name = "tf"
path = "src/main.rs"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
dirs = "6.0.0"
regex = "1.11.1"
serde_json = "1.0.140"
